name: Build ipk for HomeProxy

on:
  push:
    branches:
      - 'master'
      - 'dev'
    paths:
      - 'htdocs/**'
      - 'po/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'
      - '!.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches:
      - 'master'
      - 'dev'
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'htdocs/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'
      - '!.github/ISSUE_TEMPLATE/**'
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v4

      - name: Build ipk file
        env:
          RELEASE_TYPE: ${{ github.event_name }}
        run: |
          pushd .github
          fakeroot bash build-ipk.sh
          echo "ASSET_NAME=$(ls *.ipk)" >> $GITHUB_ENV
          popd

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.1.0
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/info.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ipk as release asset
        uses: softprops/action-gh-release@v2.1.0
        if: github.event_name == 'release'
        with:
          tag_name: ${{ github.ref_name }}
          files: .github/${{ env.ASSET_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for non-release events
        uses: actions/upload-artifact@v4
        if: github.event_name != 'release'
        with:
          name: ${{ env.ASSET_NAME }}
          path: .github/${{ env.ASSET_NAME }}
